version: "2.3"
services:
  chargeback_model:
    image: ccloud_chargeback_model
    container_name: chargeback_model
    # cpus: 1
    restart: "no"
    volumes:
    # The Output folder is the folder where you want it to aggregate the Metrics API data.
    # The folder structure will be auto created on the first run. You can then add the Billing CSV to the Billing folder for the specific org(if using multiple) to get the split output.
      - ./output:/usr/src/app/output
    # This is the folder which you can use to override the pre-coded config file. The internally available file still needs the environment variables to be configured with the API Keys for access. 
    # No credentials are hard coded into the code at all, so if you do not provide any access credentials, the code will not work.
      - ./config:/user_config
    environment:
      - CCLOUD_BILLING_API_KEY=${CCLOUD_BILLING_API_KEY}
      - CCLOUD_BILLING_API_SECRET=${CCLOUD_BILLING_API_SECRET}
    # command: [ # The below command switch will alllow you to specify your custom config file. 
    #            # The internally sourced config file relies on the ENV vars and only fetches the Chargeback related requests
    #           "--config-file","/user_config/config.yaml",
    # ]
