config:
  system:
    days_in_memory: 7
  org_details:
    - id: CCloud Org 1
      ccloud_details:
        metrics:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
        telemetry:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
      storage:
        metrics:
        billing_csv:
      requests:
        - CHARGEBACK_REQUESTS
        - id: Fetch Request Bytes
          aggregations:
            - metric: io.confluent.kafka.server/request_bytes
          granularity: PT1H
          group_by:
            - resource.kafka.id
            - metric.principal_id
          limit: 1000
          filter:
            field: resource.kafka.id
            op: EQ
            value:
              - ALL_CLUSTERS
