config:
  system:
    days_in_memory: 7
    output_dir_name: "output"
  org_details:
    - id: CCloud Org 1
      ccloud_details:
        metrics:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
        telemetry:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
      storage:
        metrics:
        billing_csv:
      requests:
        - CHARGEBACK_REQUESTS
