config:
  system:
    days_in_memory: 7
    output_dir_name: "output"
    log_level: "DEBUG"
    enable_method_breadcrumbs: False
  org_details:
    - id: CCloud Org 1
      ccloud_details:
        ccloud_api:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
        billing_api:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
        metrics_api:
          api_key: env::CCLOUD_BILLING_API_KEY
          api_secret: env::CCLOUD_BILLING_API_SECRET
      prometheus_details:
        metrics_api_datastore:
          prometheus_url: env::METRICS_API_SERVER_URL
          auth:
            enable_auth: env::METRICS_API_SERVER_ENABLE_AUTH
            auth_type: env::METRICS_API_SERVER_AUTH_TYPE
            auth_args:
              username: env::METRICS_API_SERVER_AUTH_USERNAME
              password: env::METRICS_API_SERVER_AUTH_PASSWORD
          connection_params:
            verify: False
        chargeback_datastore:
          prometheus_url: env::CHARGEBACK_SERVER_URL
